### PR TITLE
feat: add toUint8Array utility function

### LINKED ISSUE #32: toUint8Array() is not defined
```
.toUint8Array()
```

Defined in the README.md but not in the codebase.

### PR DESCRIPTION
**Pull request by paralin**
Implements `toUint8Array` as mentioned in the README.

Uses a no-copy operation if possible. Has a flag `copy` which forces a full-copy of the contents.

Fixes #32

### CODE REVIEW

**Comment by paralin** [comment]
@achingbrain added a couple minor commits to add a couple things to .gitignore and also pin the typescript version.

I had errors running "yarn test" because the Typescript on my host machine was too old (didn't support 2021.promise)

... or perhaps the typescript version required by aegir is wrong. Either way, adding "typescript" to dev dependencies fixed it.

**Comment by achingbrain** [comment]
Ah, no - what I [meant](https://github.com/achingbrain/uint8arraylist/issues/32#issuecomment-1200302653) was to just update the readme to remove references to `toUint8Array` since it doesn't exist.  Sorry to waste your time.

See #40

> I had errors running "yarn test" because the Typescript on my host machine was too old

This is a bug in yarn, or, at least, a disagreement between yarn and npm's dependency resolution algorithm.  Long story short there's another dep deep(er) in the tree that depends on an older version of Typescript that yarn hoists in preference to aegir's version which is less deep in the tree.

**Comment by paralin** [comment]
@achingbrain It's a useful function to have, no? Why not add it?

**Comment by achingbrain** [comment]
It doesn't do anything the existing methods don't do already, plus as implemented passing false as the `copy` param doesn't guarantee it'll be a no-copy operation so the user may encounter surprise.

**Pull request closed without merging**
